const ADD_NUMBER = 'ADD_NUMBER';
const SUB_NUMBER = 'SUB_NUMBER';
const CHANGE_BANNER = 'CHANGE_BANNER';
const CHANGE_RECOMMEND = 'CHANGE_RECOMMEND'
const FETCH_HOME_MULTIDATA = 'FETCH_HOME_MULTIDATA'


export {ADD_NUMBER, SUB_NUMBER, CHANGE_BANNER, CHANGE_RECOMMEND, FETCH_HOME_MULTIDATA}